//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Responsables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Responsables()
        {
            this.tbl_Responsables = new HashSet<tbl_Responsables>();
        }
    
        public int intCatResponsableId { get; set; }
        public string vchNombre { get; set; }
        public string vchApellidoPaterno { get; set; }
        public string vchApellidoMaterno { get; set; }
        public string vchRFC { get; set; }
        public bool bitResponsablePrincipal { get; set; }
        public bool bitActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Responsables> tbl_Responsables { get; set; }
    }
}
