//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CodigoFuente
    {
        public int intCodigoFuenteID { get; set; }
        public int intControlCodigoID { get; set; }
        public int intTipoCambioId { get; set; }
        public string vchRuta { get; set; }
        public string vchArchivo { get; set; }
        public int intTipoArchivo { get; set; }
        public string vchProposito { get; set; }
        public bool bitActivo { get; set; }
    
        public virtual Cat_TipoArchivo Cat_TipoArchivo { get; set; }
        public virtual Cat_TipoCambio Cat_TipoCambio { get; set; }
        public virtual tbl_ControlCambiosCodigoConfig tbl_ControlCambiosCodigoConfig { get; set; }
    }
}
