//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AreaUsuaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_AreaUsuaria()
        {
            this.tbl_Responsables = new HashSet<tbl_Responsables>();
        }
    
        public int intAreaUsuariaId { get; set; }
        public int intDatosGeneralesId { get; set; }
        public int intCatAreaUsuaria { get; set; }
    
        public virtual Cat_Areausuaria Cat_Areausuaria { get; set; }
        public virtual tbl_DatosGenerales tbl_DatosGenerales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Responsables> tbl_Responsables { get; set; }
    }
}
