//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WService.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DatosGenerales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DatosGenerales()
        {
            this.tbl_AreaUsuaria = new HashSet<tbl_AreaUsuaria>();
            this.tbl_ControlCambiosBDConfig = new HashSet<tbl_ControlCambiosBDConfig>();
            this.tbl_ControlCambiosCodigoConfig = new HashSet<tbl_ControlCambiosCodigoConfig>();
            this.tbl_Sistemas = new HashSet<tbl_Sistemas>();
        }
    
        public int intDatosGeneralesId { get; set; }
        public string vchNombreRequerimiento { get; set; }
        public string vchFolio { get; set; }
        public string vchModulo { get; set; }
        public System.DateTime sdatFechaCreacion { get; set; }
        public Nullable<int> intusuarioId { get; set; }
        public bool bitActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AreaUsuaria> tbl_AreaUsuaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ControlCambiosBDConfig> tbl_ControlCambiosBDConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ControlCambiosCodigoConfig> tbl_ControlCambiosCodigoConfig { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sistemas> tbl_Sistemas { get; set; }
    }
}
