//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWService.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_EquipoSistemas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_EquipoSistemas()
        {
            this.tbl_Sistemas = new HashSet<tbl_Sistemas>();
        }
    
        public int intEquipoSistemasId { get; set; }
        public int intCargoId { get; set; }
        public string vchNombre { get; set; }
        public string vchApellidoPaterno { get; set; }
        public string vchApellidoMaterno { get; set; }
        public string vchRFC { get; set; }
        public bool bitActivo { get; set; }
    
        public virtual Cat_CargosSistemas Cat_CargosSistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sistemas> tbl_Sistemas { get; set; }
    }
}
