//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWService.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Areausuaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Areausuaria()
        {
            this.tbl_AreaUsuaria = new HashSet<tbl_AreaUsuaria>();
        }
    
        public int intCatAreaUsuaria { get; set; }
        public string vchAreausuaria { get; set; }
        public bool bitActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AreaUsuaria> tbl_AreaUsuaria { get; set; }
    }
}
