//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWService.ModelBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbDocumentacionEntities : DbContext
    {
        public dbDocumentacionEntities()
            : base("name=dbDocumentacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           
        }
    
        public virtual DbSet<Cat_Areausuaria> Cat_Areausuaria { get; set; }
        public virtual DbSet<Cat_CargosSistemas> Cat_CargosSistemas { get; set; }
        public virtual DbSet<Cat_Clasificacion> Cat_Clasificacion { get; set; }
        public virtual DbSet<Cat_EquipoSistemas> Cat_EquipoSistemas { get; set; }
        public virtual DbSet<Cat_Modulos> Cat_Modulos { get; set; }
        public virtual DbSet<Cat_Responsables> Cat_Responsables { get; set; }
        public virtual DbSet<Cat_Servidores> Cat_Servidores { get; set; }
        public virtual DbSet<Cat_TipoArchivo> Cat_TipoArchivo { get; set; }
        public virtual DbSet<Cat_TipoCambio> Cat_TipoCambio { get; set; }
        public virtual DbSet<Cat_TipoObjeto> Cat_TipoObjeto { get; set; }
        public virtual DbSet<tbl_AreaUsuaria> tbl_AreaUsuaria { get; set; }
        public virtual DbSet<tbl_CodigoDB> tbl_CodigoDB { get; set; }
        public virtual DbSet<tbl_CodigoFuente> tbl_CodigoFuente { get; set; }
        public virtual DbSet<tbl_ControlCambiosBDConfig> tbl_ControlCambiosBDConfig { get; set; }
        public virtual DbSet<tbl_ControlCambiosCodigoConfig> tbl_ControlCambiosCodigoConfig { get; set; }
        public virtual DbSet<tbl_DatosGenerales> tbl_DatosGenerales { get; set; }
        public virtual DbSet<tbl_Responsables> tbl_Responsables { get; set; }
        public virtual DbSet<tbl_Sistemas> tbl_Sistemas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
