//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWService.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ControlCambiosCodigoConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ControlCambiosCodigoConfig()
        {
            this.tbl_CodigoFuente = new HashSet<tbl_CodigoFuente>();
        }
    
        public int intControlCodigoID { get; set; }
        public int intDatosGeneralesId { get; set; }
        public System.DateTime datFechayHoraLiberacion { get; set; }
        public int intCatServidorId { get; set; }
        public int intClasificacionID { get; set; }
        public System.DateTime datFechaElaboracion { get; set; }
        public string vchAdicionales { get; set; }
        public bool bitActivo { get; set; }
    
        public virtual Cat_Clasificacion Cat_Clasificacion { get; set; }
        public virtual Cat_Servidores Cat_Servidores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CodigoFuente> tbl_CodigoFuente { get; set; }
        public virtual tbl_DatosGenerales tbl_DatosGenerales { get; set; }
    }
}
