//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWService.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sistemas
    {
        public int intSistemasId { get; set; }
        public int intDatosGeneralesId { get; set; }
        public int intEquipoSistemasId { get; set; }
    
        public virtual Cat_EquipoSistemas Cat_EquipoSistemas { get; set; }
        public virtual tbl_DatosGenerales tbl_DatosGenerales { get; set; }
    }
}
