//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWService.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CodigoDB
    {
        public int intCodigoDBID { get; set; }
        public int intControlBDID { get; set; }
        public int intTipoCambioId { get; set; }
        public int intTipoObjeto { get; set; }
        public string vchBase { get; set; }
        public int intOrden { get; set; }
        public string vchNombreObjeto { get; set; }
        public string vchDescripcion { get; set; }
        public string vchRuta { get; set; }
        public bool bitActivo { get; set; }
    
        public virtual Cat_TipoCambio Cat_TipoCambio { get; set; }
        public virtual Cat_TipoObjeto Cat_TipoObjeto { get; set; }
        public virtual tbl_ControlCambiosBDConfig tbl_ControlCambiosBDConfig { get; set; }
    }
}
